### ISSUE TITLE
Activate *edit mode* by clicking on  a secondary element

### ISSUE THREAD

**Issue by movstox** [swastik/ember-inline-edit#1]
Thanks for great addon!

Just a question, is there a way to activate *edit mode* by secondary element (i.e. clicking on 'edit' button or 'pencil' icon)?

Best regards.

**Comment by swastik** [comment]
Thanks for the issue! :smile:

There's no way for that yet, but I'll push an update later today to handle this. :)

**Comment by swastik** [comment]
Just pushed an update. You can now pass a `showEditButton` attribute and it'll show an icon that can toggle the edit mode. Let me know if you want any other changes. :smile:

**Comment by movstox** [comment]
This looks great. What do you think about the idea of controlling edit mode via Boolean component parameter? This would allow activating the component via clicking on just about anything...

--

**Comment by swastik** [comment]
Inside the component, the mode is controlled by the `isEditing` parameter
which is a boolean. Do you mean exposing this as an attribute that can be
controlled from the outside?

- Swastik

**Comment by movstox** [comment]
Yup!

--

**Comment by swastik** [comment]
You can already do that by sending in the `isEditing=someProperty` attribute. So if `someProperty` is true, it goes into `isEditing` mode and if it's not, the opposite.

I'll check the code to see if anything might need a change to suit this. :smile:

**Comment by movstox** [comment]
Thanks, everything looks great!

--
