### ISSUE TITLE
Hints for rollback?

### ISSUE THREAD

**Issue by sarupbanskota** [swastik/ember-inline-edit#11]
Hello folks, thanks for the awesome work on this addon!

I wanted to do a `rollback` feature through which, any changes get undone once `onClose` is triggered.

```
 rollback(id, prop, prevContent) {
    let obj = this.get('store').peekRecord(model, id);	   
    obj.set(prop, prevContent);
 },
```

I thought of doing something like that, but didn't quite work out. Any tips / examples?

**Comment by swastik** [comment]
Hi Sarup, thanks for the question! 😄 

The `prevContent` is actually not sent as an argument which is probably why this isn't working. You may want to try `[rollbackAttributes](http://emberjs.com/api/data/classes/DS.Model.html#method_rollbackAttributes)` on the model if you want to rollback all the changes or just `[resetAttribute(attributeName)](http://emberjs.com/api/data/classes/DS.Model.html#method_resetAttribute)` if you want to rollback a single attribute.

Let me know if that works.

**Comment by sarupbanskota** [comment]
Hello again @swastik!

> The prevContent is actually not sent as an argument which is probably why this isn't working

Although it was being passed, your comment gave me a hint - turns out my function was expecting args in the order x, y, z and I was calling it as y, x, z 

How silly! Got it working now, `obj.set()` worked fine :-)

Thank you! Closing this.
