### ISSUE TITLE
is-hidden CSS class being applied by default

### ISSUE THREAD

**Issue by ryanjavens** [swastik/ember-inline-edit#18]
Version: 0.2.1
Ember version: 2.13.0

I took your example from your documentation and it seems that the default behavior is to hide the ember-inline-editable component. If I go into dev tools and disable the `display:none` property on `.is-hidden` and click on the text to edit, it looks that the parent div of the input field is also defaulting to hidden. I'm not sure if this is a bug or if I'm just missing some way to override this, but I'd appreciate any input! 

Thank you!

**Comment by swastik** [comment]
@ryanjavens Good catch! It seems like some of the components internally didn't pass in the isVisible flag, so it set itself to `is-hidden` and since `is-hidden` isn't in our CSS, our tests didn't catch it. I'll fix this and push a release today.

**Comment by swastik** [comment]
Whoops, didn't mean to close this. I've pushed a fix for this, should be released in a bit.

**Comment by swastik** [comment]
@ryanjavens Okay, I pushed a new version [`1.0.0-beta.1`](https://www.npmjs.com/package/ember-inline-edit) that takes care of this. Sorry about this and let me know if that works! I tested it on ember 2.13.0 and it seemed to be fine. 😅

**Comment by ryanjavens** [comment]
@swastik looks all good to me now! Thank you so much!

**Comment by swastik** [comment]
@ryanjavens Thanks — closing this now! 👍
