### ISSUE TITLE
[Feature Request] Allow save instead of revert onClickOutside 

### ISSUE THREAD

**Issue by Alonski** [swastik/ember-inline-edit#29]
Currently, this component is set up to revert changes when doing focusOut while editing.

I propose adding an option for `saveOnFocusOut`. 
When this is true then instead of canceling we then save.

The change needs to be here:
https://github.com/swastik/ember-inline-edit/blob/master/addon/components/ember-inline-edit.js#L63

**Comment by swastik** [comment]
Thanks for creating this issue, @Alonski! I've got a branch that should give you more control over this: https://github.com/swastik/ember-inline-edit/pull/31

I'll get that released in a bit.

**Comment by Alonski** [comment]
Awesome work @swastik Thanks a lot!
Can't wait to see this merged

**Comment by swastik** [comment]
It's been released in 1.2.0, @Alonski!

**Comment by Alonski** [comment]
Thanks a lot!
