### ISSUE TITLE
event argument is null when called with .send

### ISSUE THREAD

**Issue by jschilli** [swastik/ember-inline-edit#6]
I haven't had time yet to isolate this but in our usage (without the edit button) `e` is null so this line bombs.

https://github.com/swastik/ember-inline-edit/blob/master/addon/components/ember-inline-edit.js#L93

It may well be this line (that is not propogating the event) https://github.com/swastik/ember-inline-edit/blob/master/addon/components/ember-inline-edit.js#L56

I'll try to work up a test case but dropping back to 0.1.5 resolves this for me.

**Comment by swastik** [comment]
Thanks for reporting! I'll take a look.

**Comment by swastik** [comment]
You were actually right... that was my oversight. The `_handleClick` function not propagating the event and the tests were failing too.

It is fixed and published now, in `0.1.7`. It should work, but if there are any problems, please let me know.

Thanks once again for reporting! 😄
